ALTER TABLE IF EXISTS departments ALTER COLUMN faculty_id DROP NOT NULL;
ALTER TABLE  IF EXISTS groups ALTER COLUMN department_id DROP NOT NULL;
ALTER TABLE IF EXISTS students ALTER COLUMN group_id DROP NOT NULL;
