ALTER TABLE faculties ADD COLUMN IF NOT EXISTS deleted BOOLEAN;
UPDATE faculties SET deleted = 'false';
ALTER TABLE faculties ALTER COLUMN deleted SET NOT NULL;
ALTER TABLE faculties ALTER COLUMN deleted SET DEFAULT FALSE;

ALTER TABLE departments ADD COLUMN IF NOT EXISTS deleted BOOLEAN;
UPDATE departments SET deleted = 'false';
ALTER TABLE departments ALTER COLUMN deleted SET NOT NULL;
ALTER TABLE departments ALTER COLUMN deleted SET DEFAULT FALSE;

ALTER TABLE groups ADD COLUMN IF NOT EXISTS deleted BOOLEAN;
UPDATE groups SET deleted = 'false';
ALTER TABLE groups ALTER COLUMN deleted SET NOT NULL;
ALTER TABLE groups ALTER COLUMN deleted SET DEFAULT FALSE;

ALTER TABLE students ADD COLUMN IF NOT EXISTS deleted BOOLEAN;
UPDATE students SET deleted = 'false';
ALTER TABLE students ALTER COLUMN deleted SET NOT NULL;
ALTER TABLE students ALTER COLUMN deleted SET DEFAULT FALSE;
